//! psd-tools knockout differential oracle for `pictura_render::composite_rgba`.
//!
//! `knockout.psd` (authored by `scripts/generate-fixtures.py`) holds a red
//! Background, an intermediate green layer, and a half-fill blue layer carrying
//! `knko = Deep`. `psd-tools`' own compositor implements deep knockout
//! (`psd_tools/composite/composite.py`, "Verified against Photoshop"), so a raw
//! interleaved-RGBA8 reference generated by `scripts/psd_knockout_reference.py`
//! is an independent oracle for the CPU path. This test reads the fixture
//! through `read_psd`, asserts the typed `Knockout::Deep`, composites with
//! `composite_rgba`, and diffs against the reference. Self-skips without
//! `psd_tools`, like the other oracles.
//!
//! Tolerance 1: psd-tools floors the 8-bit result while the CPU compositor
//! rounds, so the two differ by at most one LSB (the half-fill blue over red
//! lands on 126 vs 127). A larger disagreement is a behavior bug, not rounding,
//! and must be reported rather than absorbed.
//!
//! Regenerate the reference with
//! `python3 scripts/psd_knockout_reference.py gen`.

use std::path::PathBuf;
use std::process::Command;

use pictura_core::Knockout;
use pictura_testkit::compare;

/// One LSB of 8-bit rounding between psd-tools' floor and the CPU's round.
const TOLERANCE: u8 = 1;

fn reference_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/knockout_deep.rgba")
}

fn psd_tools_available() -> bool {
    static AVAILABLE: std::sync::OnceLock<bool> = std::sync::OnceLock::new();
    *AVAILABLE.get_or_init(|| {
        Command::new("python3")
            .args(["-c", "import psd_tools"])
            .output()
            .map(|o| o.status.success())
            .unwrap_or(false)
    })
}

/// Flatten a planar RGBA `PixelBuffer` to the interleaved layout the reference
/// stores (matching `tests/oracle.rs`'s `interleaved`).
fn interleaved(buf: &pictura_core::PixelBuffer) -> Vec<u8> {
    let pixels = buf.pixel_count();
    assert_eq!(buf.channels, 4, "composite_rgba must return RGBA");
    let mut out = vec![0u8; pixels * 4];
    for i in 0..pixels {
        for c in 0..4usize {
            out[i * 4 + c] = buf.data[c * pixels + i];
        }
    }
    out
}

#[test]
fn knockout_composite_matches_psd_tools() {
    if !psd_tools_available() {
        eprintln!("skipping psd-tools check: python3 + psd_tools not available");
        return;
    }

    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../pictura-codec/tests/fixtures/knockout.psd");
    let bytes = std::fs::read(&path).unwrap_or_else(|e| panic!("read {}: {e}", path.display()));
    let doc = pictura_codec::read_psd(&bytes).expect("fixture parses");

    let top = doc.layers.last().expect("top layer");
    assert_eq!(
        top.knockout,
        Knockout::Deep,
        "top layer {:?} must decode as Deep",
        top.name
    );

    let actual = interleaved(&pictura_render::composite_rgba(&doc));
    let reference = std::fs::read(reference_path()).unwrap_or_else(|e| {
        panic!("cannot read reference ({e}); run `python3 scripts/psd_knockout_reference.py gen`")
    });

    let diff = compare(&actual, &reference, TOLERANCE).unwrap_or_else(|e| panic!("{e}"));
    assert!(
        diff.is_empty(),
        "knockout composite differs from psd-tools by up to {} LSB over {} samples \
         (mean {:.3}); tolerance {TOLERANCE}, not widened on purpose",
        diff.max_delta,
        diff.differing,
        diff.mean_delta()
    );

    // Independent of tolerance: the deep knockout punches the intermediate
    // green through, so its channel is exactly zero at a covered pixel.
    assert_eq!(
        actual[1],
        0,
        "intermediate green must be punched through, got pixel {:?}",
        &actual[0..4]
    );
}
