//! psd-tools knockout differential oracle for `pictura_render::composite_rgba`.
//!
//! `knockout.psd` (authored by `scripts/generate-fixtures.py`) holds a red
//! Background, an intermediate green layer, and a half-fill blue layer carrying
//! `knko = Deep`. `psd-tools`' own compositor implements deep knockout
//! (`psd_tools/composite/composite.py`, that project's verified compositor), so a raw
//! interleaved-RGBA8 reference generated by `scripts/psd_knockout_reference.py`
//! is an independent oracle for the CPU path. This test reads the fixture
//! through `read_psd`, asserts the typed `Knockout::Deep`, composites with
//! `composite_rgba`, and diffs against the reference. Self-skips without
//! `psd_tools`, like the other oracles.
//!
//! Tolerance 1: psd-tools floors the 8-bit result while the CPU compositor
//! rounds, so the two differ by at most one LSB (the half-fill blue over red
//! lands on 126 vs 127). A larger disagreement is a behavior bug, not rounding,
//! and must be reported rather than absorbed.
//!
//! Regenerate the reference with
//! `python3 scripts/psd_knockout_reference.py gen`.

use std::path::PathBuf;
use std::process::Command;

use pictura_core::{BlendMode, Knockout};
use pictura_testkit::compare;

/// One LSB of 8-bit rounding between psd-tools' floor and the CPU's round.
const TOLERANCE: u8 = 1;

fn reference_path(stem: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests/fixtures")
        .join(format!("{stem}.rgba"))
}

fn psd_tools_available() -> bool {
    static AVAILABLE: std::sync::OnceLock<bool> = std::sync::OnceLock::new();
    *AVAILABLE.get_or_init(|| {
        Command::new("python3")
            .args(["-c", "import psd_tools"])
            .output()
            .map(|o| o.status.success())
            .unwrap_or(false)
    })
}

/// `psd-tools` >= 1.19 is the first release whose compositor discriminates
/// `Shallow` from `Deep` (`_knockout_backdrop`), so an older reference cannot
/// verify this case and the Shallow oracle must self-skip rather than pass for
/// the wrong reason.
fn psd_tools_shallow_aware() -> bool {
    static AVAILABLE: std::sync::OnceLock<bool> = std::sync::OnceLock::new();
    *AVAILABLE.get_or_init(|| {
        Command::new("python3")
            .args([
                "-c",
                "import importlib.metadata as m, sys; \
                 v = tuple(int(p) for p in m.version('psd-tools').split('.')[:2]); \
                 sys.exit(0 if v >= (1, 19) else 1)",
            ])
            .output()
            .map(|o| o.status.success())
            .unwrap_or(false)
    })
}

/// Flatten a planar RGBA `PixelBuffer` to the interleaved layout the reference
/// stores (matching `tests/oracle.rs`'s `interleaved`).
fn interleaved(buf: &pictura_core::PixelBuffer) -> Vec<u8> {
    let pixels = buf.pixel_count();
    assert_eq!(buf.channels, 4, "composite_rgba must return RGBA");
    let mut out = vec![0u8; pixels * 4];
    for i in 0..pixels {
        for c in 0..4usize {
            out[i * 4 + c] = buf.data[c * pixels + i];
        }
    }
    out
}

#[test]
fn knockout_composite_matches_psd_tools() {
    if !psd_tools_available() {
        eprintln!("skipping psd-tools check: python3 + psd_tools not available");
        return;
    }

    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../pictura-codec/tests/fixtures/knockout.psd");
    let bytes = std::fs::read(&path).unwrap_or_else(|e| panic!("read {}: {e}", path.display()));
    let doc = pictura_codec::read_psd(&bytes).expect("fixture parses");

    let top = doc.layers.last().expect("top layer");
    assert_eq!(
        top.knockout,
        Knockout::Deep,
        "top layer {:?} must decode as Deep",
        top.name
    );

    let actual = interleaved(&pictura_render::composite_rgba(&doc));
    let reference = std::fs::read(reference_path("knockout_deep")).unwrap_or_else(|e| {
        panic!("cannot read reference ({e}); run `python3 scripts/psd_knockout_reference.py gen`")
    });

    let diff = compare(&actual, &reference, TOLERANCE).unwrap_or_else(|e| panic!("{e}"));
    assert!(
        diff.is_empty(),
        "knockout composite differs from psd-tools by up to {} LSB over {} samples \
         (mean {:.3}); tolerance {TOLERANCE}, not widened on purpose",
        diff.max_delta,
        diff.differing,
        diff.mean_delta()
    );

    // Independent of tolerance: the deep knockout punches the intermediate
    // green through, so its channel is exactly zero at a covered pixel.
    assert_eq!(
        actual[1],
        0,
        "intermediate green must be punched through, got pixel {:?}",
        &actual[0..4]
    );
}

/// The same differential check for `knockout_group.psd`: a red Background, a
/// **pass-through** group of green and a half-fill `knko = Deep` blue. The
/// fixture is authored so psd-tools writes the folder as `pass`; the test
/// asserts the typed `PassThrough` blend so a silently-isolated fixture fails
/// loudly instead of passing for the wrong reason.
#[test]
fn knockout_in_pass_through_group_matches_psd_tools() {
    if !psd_tools_available() {
        eprintln!("skipping psd-tools check: python3 + psd_tools not available");
        return;
    }

    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../pictura-codec/tests/fixtures/knockout_group.psd");
    let bytes = std::fs::read(&path).unwrap_or_else(|e| panic!("read {}: {e}", path.display()));
    let doc = pictura_codec::read_psd(&bytes).expect("fixture parses");

    let group = doc.layers.last().expect("top group");
    assert!(
        group.is_group && group.blend == BlendMode::PassThrough,
        "top layer {:?} must decode as a pass-through group (blend {:?}, group {})",
        group.name,
        group.blend,
        group.is_group
    );
    let child = group.children.last().expect("knockout child");
    assert_eq!(
        child.knockout,
        Knockout::Deep,
        "child {:?} must decode as Deep",
        child.name
    );

    let actual = interleaved(&pictura_render::composite_rgba(&doc));
    let reference = std::fs::read(reference_path("knockout_group")).unwrap_or_else(|e| {
        panic!(
            "cannot read reference ({e}); run `python3 scripts/psd_knockout_reference.py gen \
             --out crates/pictura-render/tests/fixtures/knockout_group.rgba`"
        )
    });

    let diff = compare(&actual, &reference, TOLERANCE).unwrap_or_else(|e| panic!("{e}"));
    assert!(
        diff.is_empty(),
        "group knockout composite differs from psd-tools by up to {} LSB over {} samples \
         (mean {:.3}); tolerance {TOLERANCE}, not widened on purpose",
        diff.max_delta,
        diff.differing,
        diff.mean_delta()
    );

    // Independent of tolerance: the group's intermediate green is punched
    // through to the red background, with the half-fill blue on top.
    assert_eq!(
        actual[1],
        0,
        "group green must be punched through, got pixel {:?}",
        &actual[0..4]
    );
    assert!(
        actual[0] > 0,
        "red background shows through, got {:?}",
        &actual[0..4]
    );
    assert!(
        actual[2] > 0,
        "blue knockout layer is present, got {:?}",
        &actual[0..4]
    );
}

/// The differential check for `knockout_isolated_group.psd`: a red Background, a
/// yellow layer, then an **isolated** (explicit Normal) group of green and a
/// half-fill `knko = Deep` blue. psd-tools stops the deep knockout at the
/// isolated group, so the group's green is punched through to the group's
/// transparent initial backdrop and the group then blends over the yellow below
/// it. The test asserts the decoded group is not `PassThrough` (a silently
/// pass-through fixture would give the wrong `(126, 0, 128)`) and the child is
/// `Deep`, then diffs against the reference.
#[test]
fn knockout_in_isolated_group_matches_psd_tools() {
    if !psd_tools_available() {
        eprintln!("skipping psd-tools check: python3 + psd_tools not available");
        return;
    }

    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../pictura-codec/tests/fixtures/knockout_isolated_group.psd");
    let bytes = std::fs::read(&path).unwrap_or_else(|e| panic!("read {}: {e}", path.display()));
    let doc = pictura_codec::read_psd(&bytes).expect("fixture parses");

    let group = doc.layers.last().expect("top group");
    assert!(
        group.is_group && group.blend != BlendMode::PassThrough,
        "top layer {:?} must decode as an isolated group (blend {:?}, group {})",
        group.name,
        group.blend,
        group.is_group
    );
    let child = group.children.last().expect("knockout child");
    assert_eq!(
        child.knockout,
        Knockout::Deep,
        "child {:?} must decode as Deep",
        child.name
    );

    let actual = interleaved(&pictura_render::composite_rgba(&doc));
    let reference = std::fs::read(reference_path("knockout_isolated_group")).unwrap_or_else(|e| {
        panic!(
            "cannot read reference ({e}); run `python3 scripts/psd_knockout_reference.py gen \
             --out crates/pictura-render/tests/fixtures/knockout_isolated_group.rgba`"
        )
    });

    let diff = compare(&actual, &reference, TOLERANCE).unwrap_or_else(|e| panic!("{e}"));
    assert!(
        diff.is_empty(),
        "isolated-group knockout differs from psd-tools by up to {} LSB over {} samples \
         (mean {:.3}); tolerance {TOLERANCE}, not widened on purpose",
        diff.max_delta,
        diff.differing,
        diff.mean_delta()
    );

    // Independent of tolerance: the group's green is punched through to the
    // group's initial backdrop, so the green the pixel shows comes only from the
    // yellow layer below the group. A deep knockout that reached the document
    // background (red) would leave green at zero.
    assert!(
        actual[1] > 0,
        "the yellow layer below the group contributes green, got pixel {:?}",
        &actual[0..4]
    );
    assert!(
        actual[0] > 0,
        "the layer below the group contributes red, got {:?}",
        &actual[0..4]
    );
    assert!(
        actual[2] > 0,
        "blue knockout layer is present, got {:?}",
        &actual[0..4]
    );
}

/// The differential check for `knockout_shallow_group.psd`: a red Background, an
/// opaque yellow intervening layer, then a **pass-through** group of green and a
/// half-fill `knko = Shallow` blue. Shallow knockout stops at the group's entry
/// backdrop (red-plus-yellow), so the group's green is punched through but the
/// yellow below the group still contributes; a `Deep` knockout would instead
/// reveal red and leave the pixel's green at zero. The test asserts the decoded
/// group is `PassThrough` and the child is `Shallow`, self-skipping when
/// `psd-tools` is unavailable or older than 1.19 (which cannot discriminate
/// Shallow), then diffs against the reference.
#[test]
fn knockout_shallow_in_pass_through_group_matches_psd_tools() {
    if !psd_tools_shallow_aware() {
        eprintln!("skipping psd-tools Shallow check: python3 + psd-tools>=1.19 not available");
        return;
    }

    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../pictura-codec/tests/fixtures/knockout_shallow_group.psd");
    let bytes = std::fs::read(&path).unwrap_or_else(|e| panic!("read {}: {e}", path.display()));
    let doc = pictura_codec::read_psd(&bytes).expect("fixture parses");

    let group = doc.layers.last().expect("top group");
    assert!(
        group.is_group && group.blend == BlendMode::PassThrough,
        "top layer {:?} must decode as a pass-through group (blend {:?}, group {})",
        group.name,
        group.blend,
        group.is_group
    );
    let child = group.children.last().expect("knockout child");
    assert_eq!(
        child.knockout,
        Knockout::Shallow,
        "child {:?} must decode as Shallow",
        child.name
    );

    let actual = interleaved(&pictura_render::composite_rgba(&doc));
    let reference = std::fs::read(reference_path("knockout_shallow_group")).unwrap_or_else(|e| {
        panic!(
            "cannot read reference ({e}); run `python3 scripts/psd_knockout_reference.py gen \
             --out crates/pictura-render/tests/fixtures/knockout_shallow_group.rgba`"
        )
    });

    let diff = compare(&actual, &reference, TOLERANCE).unwrap_or_else(|e| panic!("{e}"));
    assert!(
        diff.is_empty(),
        "shallow-group knockout differs from psd-tools by up to {} LSB over {} samples \
         (mean {:.3}); tolerance {TOLERANCE}, not widened on purpose",
        diff.max_delta,
        diff.differing,
        diff.mean_delta()
    );

    // Independent of tolerance: Shallow stops at the group backdrop, so the
    // group's green is punched through but the yellow below contributes. A Deep
    // knockout reaching the red background would leave this pixel's green at
    // zero.
    assert!(
        actual[1] > 0,
        "the yellow layer below the group contributes green, got pixel {:?}",
        &actual[0..4]
    );
    assert!(
        actual[0] > 0,
        "the layer below the group contributes red, got {:?}",
        &actual[0..4]
    );
    assert!(
        actual[2] > 0,
        "blue knockout layer is present, got {:?}",
        &actual[0..4]
    );
}
