use pictura_core::PixelBuffer;

use crate::{
    artistic, blur, brush_strokes, distort, noise, oil_paint, other, pixelate, render, sharpen,
    sketch, stylize, texture, validate, FilterError,
};

use super::Filter;

/// Apply `filter` in place (planar 8-bit; channels 3 or 4; alpha untouched).
pub fn apply(filter: &Filter, buf: &mut PixelBuffer) -> Result<(), FilterError> {
    validate(buf)?;
    match filter {
        Filter::GaussianBlur { radius } => blur::gaussian(buf, *radius),
        Filter::BoxBlur { radius } => blur::r#box(buf, *radius),
        Filter::MotionBlur { angle, distance } => blur::motion(buf, *angle, *distance),
        Filter::RadialBlur {
            method,
            amount,
            quality,
        } => blur::radial(buf, *method, *amount, *quality),
        Filter::Average => blur::average(buf),
        Filter::Blur => blur::simple(buf, false),
        Filter::BlurMore => blur::simple(buf, true),
        Filter::SurfaceBlur { radius, threshold } => blur::surface(buf, *radius, *threshold),
        Filter::Sharpen => sharpen::sharpen(buf),
        Filter::SharpenMore => sharpen::sharpen_more(buf),
        Filter::SharpenEdges => sharpen::edges(buf),
        Filter::UnsharpMask {
            amount,
            radius,
            threshold,
        } => sharpen::unsharp_mask(buf, *amount, *radius, *threshold),
        Filter::AddNoise {
            amount,
            distribution,
            monochromatic,
            seed,
        } => noise::add(buf, *amount, *distribution, *monochromatic, *seed),
        Filter::Median { radius } => noise::median(buf, *radius),
        Filter::Despeckle => noise::despeckle(buf),
        Filter::Maximum { radius } => other::maximum(buf, *radius),
        Filter::Minimum { radius } => other::minimum(buf, *radius),
        Filter::Offset {
            horizontal,
            vertical,
            wrap,
            background,
        } => other::offset(buf, *horizontal, *vertical, *wrap, *background),
        Filter::HighPass { radius } => other::high_pass(buf, *radius),
        Filter::Custom {
            kernel,
            scale,
            offset,
        } => other::custom(buf, kernel, *scale, *offset),
        Filter::Emboss {
            angle,
            height,
            amount,
        } => stylize::emboss(buf, *angle, *height, *amount),
        Filter::FindEdges => stylize::find_edges(buf),
        Filter::Solarize => stylize::solarize(buf),
        Filter::Diffuse { mode } => stylize::diffuse(buf, *mode),
        Filter::GlowingEdges {
            width,
            brightness,
            smoothness,
        } => stylize::glowing_edges(buf, *width, *brightness, *smoothness),
        Filter::Mosaic { cell_size } => pixelate::mosaic(buf, *cell_size),
        Filter::Crystallize { cell_size, seed } => pixelate::crystallize(buf, *cell_size, *seed),
        Filter::Facet => pixelate::facet(buf),
        Filter::Fragment => pixelate::fragment(buf),
        Filter::Mezzotint { kind, seed } => pixelate::mezzotint(buf, *kind, *seed),
        Filter::Pointillize {
            cell_size,
            background,
            seed,
        } => pixelate::pointillize(buf, *cell_size, *background, *seed),
        Filter::ColorHalftone { max_radius, angles } => {
            pixelate::color_halftone(buf, *max_radius, *angles)
        }
        Filter::Twirl { angle } => distort::twirl(buf, *angle),
        Filter::Pinch { amount } => distort::pinch(buf, *amount),
        Filter::Spherize { amount, mode } => distort::spherize(buf, *amount, *mode),
        Filter::Ripple { amount, size } => distort::ripple(buf, *amount, *size),
        Filter::Wave {
            generators,
            wavelength,
            amplitude,
            kind,
            scale,
            seed,
            repeat_edge,
        } => distort::wave(
            buf,
            *generators,
            *wavelength,
            *amplitude,
            *kind,
            *scale,
            *seed,
            *repeat_edge,
        ),
        Filter::PolarCoordinates { kind } => distort::polar_coordinates(buf, *kind),
        Filter::Shear { curve, fill } => distort::shear(buf, curve, *fill),
        Filter::ZigZag {
            amount,
            ridges,
            style,
        } => distort::zigzag(buf, *amount, *ridges, *style),
        Filter::OceanRipple {
            size,
            magnitude,
            seed,
        } => distort::ocean_ripple(buf, *size, *magnitude, *seed),
        Filter::Clouds {
            color_a,
            color_b,
            starker,
            seed,
        } => render::clouds(buf, *color_a, *color_b, *starker, *seed),
        Filter::DifferenceClouds {
            color_a,
            color_b,
            starker,
            seed,
        } => render::difference_clouds(buf, *color_a, *color_b, *starker, *seed),
        Filter::Fibers {
            variance,
            strength,
            color_a,
            color_b,
            seed,
        } => render::fibers(buf, *variance, *strength, *color_a, *color_b, *seed),
        Filter::LensFlare {
            brightness,
            center,
            lens,
        } => render::lens_flare(buf, *brightness, *center, *lens),
        Filter::Lighting { lighting } => render::lighting_effects(buf, lighting),
        Filter::Cutout {
            levels,
            edge_simplicity,
            edge_fidelity,
        } => artistic::cutout(buf, *levels, *edge_simplicity, *edge_fidelity),
        Filter::FilmGrain {
            grain,
            highlight_area,
            intensity,
            seed,
        } => artistic::film_grain(buf, *grain, *highlight_area, *intensity, *seed),
        Filter::NeonGlow {
            glow_size,
            glow_brightness,
            glow_color,
        } => artistic::neon_glow(buf, *glow_size, *glow_brightness, *glow_color),
        Filter::PosterEdges {
            edge_thickness,
            edge_intensity,
            posterization,
        } => artistic::poster_edges(buf, *edge_thickness, *edge_intensity, *posterization),
        Filter::PaintDaubs {
            brush_size,
            sharpness,
            brush_type,
            seed,
        } => artistic::paint_daubs(buf, *brush_size, *sharpness, *brush_type, *seed),
        Filter::PaletteKnife {
            stroke_size,
            stroke_detail,
            softness,
            seed,
        } => artistic::palette_knife(buf, *stroke_size, *stroke_detail, *softness, *seed),
        Filter::PlasticWrap {
            highlight_strength,
            detail,
            smoothness,
        } => artistic::plastic_wrap(buf, *highlight_strength, *detail, *smoothness),
        Filter::Sponge {
            brush_size,
            definition,
            smoothness,
            seed,
        } => artistic::sponge(buf, *brush_size, *definition, *smoothness, *seed),
        Filter::ColoredPencil {
            pencil_width,
            stroke_pressure,
            paper_brightness,
            foreground,
            background,
            seed,
        } => artistic::colored_pencil(
            buf,
            *pencil_width,
            *stroke_pressure,
            *paper_brightness,
            *foreground,
            *background,
            *seed,
        ),
        Filter::DryBrush {
            brush_size,
            brush_detail,
            texture,
            seed,
        } => artistic::dry_brush(buf, *brush_size, *brush_detail, *texture, *seed),
        Filter::Fresco {
            brush_size,
            brush_detail,
            texture,
            seed,
        } => artistic::fresco(buf, *brush_size, *brush_detail, *texture, *seed),
        Filter::RoughPastels {
            stroke_length,
            stroke_detail,
            texture,
            foreground,
            background,
            seed,
        } => artistic::rough_pastels(
            buf,
            *stroke_length,
            *stroke_detail,
            *texture,
            *foreground,
            *background,
            *seed,
        ),
        Filter::SmudgeStick {
            stroke_length,
            highlight_area,
            intensity,
            seed,
        } => artistic::smudge_stick(buf, *stroke_length, *highlight_area, *intensity, *seed),
        Filter::Underpainting {
            brush_size,
            texture_coverage,
            texture,
            seed,
        } => artistic::underpainting(buf, *brush_size, *texture_coverage, *texture, *seed),
        Filter::Watercolor {
            brush_detail,
            shadow_intensity,
            texture,
            foreground,
            background,
            seed,
        } => artistic::watercolor(
            buf,
            *brush_detail,
            *shadow_intensity,
            *texture,
            *foreground,
            *background,
            *seed,
        ),
        Filter::AccentedEdges {
            edge_width,
            edge_brightness,
            smoothness,
        } => brush_strokes::accented_edges(buf, *edge_width, *edge_brightness, *smoothness),
        Filter::AngledStrokes {
            direction_balance,
            stroke_length,
            sharpness,
        } => brush_strokes::angled_strokes(buf, *direction_balance, *stroke_length, *sharpness),
        Filter::Crosshatch {
            stroke_length,
            sharpness,
            strength,
        } => brush_strokes::crosshatch(buf, *stroke_length, *sharpness, *strength),
        Filter::DarkStrokes {
            balance,
            black_intensity,
            white_intensity,
        } => brush_strokes::dark_strokes(buf, *balance, *black_intensity, *white_intensity),
        Filter::InkOutlines {
            stroke_length,
            dark_intensity,
            light_intensity,
        } => brush_strokes::ink_outlines(buf, *stroke_length, *dark_intensity, *light_intensity),
        Filter::Spatter {
            spray_radius,
            smoothness,
            seed,
        } => brush_strokes::spatter(buf, *spray_radius, *smoothness, *seed),
        Filter::SprayedStrokes {
            stroke_length,
            spray_radius,
            direction,
            seed,
        } => brush_strokes::sprayed_strokes(buf, *stroke_length, *spray_radius, *direction, *seed),
        Filter::SumiE {
            stroke_width,
            stroke_pressure,
            contrast,
        } => brush_strokes::sumi_e(buf, *stroke_width, *stroke_pressure, *contrast),
        Filter::BasRelief {
            detail,
            smoothness,
            light_direction,
            foreground,
            background,
        } => sketch::bas_relief(
            buf,
            *detail,
            *smoothness,
            *light_direction,
            *foreground,
            *background,
        ),
        Filter::ChalkCharcoal {
            charcoal_area,
            chalk_area,
            stroke_pressure,
            foreground,
            background,
            seed,
        } => sketch::chalk_charcoal(
            buf,
            *charcoal_area,
            *chalk_area,
            *stroke_pressure,
            *foreground,
            *background,
            *seed,
        ),
        Filter::Charcoal {
            thickness,
            detail,
            light_dark_balance,
            foreground,
            background,
            seed,
        } => sketch::charcoal(
            buf,
            *thickness,
            *detail,
            *light_dark_balance,
            *foreground,
            *background,
            *seed,
        ),
        Filter::Chrome { detail, smoothness } => sketch::chrome(buf, *detail, *smoothness),
        Filter::ConteCrayon {
            foreground_level,
            background_level,
            texture,
            foreground,
            background,
            seed,
        } => sketch::conte_crayon(
            buf,
            *foreground_level,
            *background_level,
            *texture,
            *foreground,
            *background,
            *seed,
        ),
        Filter::GraphicPen {
            stroke_length,
            light_dark_balance,
            direction,
            foreground,
            background,
        } => sketch::graphic_pen(
            buf,
            *stroke_length,
            *light_dark_balance,
            *direction,
            *foreground,
            *background,
        ),
        Filter::HalftonePattern {
            size,
            contrast,
            pattern,
        } => sketch::halftone_pattern(buf, *size, *contrast, *pattern),
        Filter::NotePaper {
            image_balance,
            graininess,
            relief,
            seed,
        } => sketch::note_paper(buf, *image_balance, *graininess, *relief, *seed),
        Filter::Photocopy { detail, darkness } => sketch::photocopy(buf, *detail, *darkness),
        Filter::Plaster {
            image_balance,
            smoothness,
            light_direction,
            foreground,
            background,
        } => sketch::plaster(
            buf,
            *image_balance,
            *smoothness,
            *light_direction,
            *foreground,
            *background,
        ),
        Filter::Reticulation {
            density,
            black_level,
            white_level,
            foreground,
            background,
            seed,
        } => sketch::reticulation(
            buf,
            *density,
            *black_level,
            *white_level,
            *foreground,
            *background,
            *seed,
        ),
        Filter::Stamp {
            light_dark_balance,
            smoothness,
            foreground,
            background,
        } => sketch::stamp(
            buf,
            *light_dark_balance,
            *smoothness,
            *foreground,
            *background,
        ),
        Filter::TornEdges {
            image_balance,
            smoothness,
            contrast,
            foreground,
            background,
        } => sketch::torn_edges(
            buf,
            *image_balance,
            *smoothness,
            *contrast,
            *foreground,
            *background,
        ),
        Filter::WaterPaper {
            fiber_length,
            brightness,
            contrast,
            seed,
        } => sketch::water_paper(buf, *fiber_length, *brightness, *contrast, *seed),
        Filter::Craquelure {
            crack_spacing,
            crack_depth,
            crack_brightness,
        } => texture::craquelure(buf, *crack_spacing, *crack_depth, *crack_brightness),
        Filter::Grain {
            intensity,
            contrast,
            grain_type,
            background,
            seed,
        } => texture::grain(buf, *intensity, *contrast, *grain_type, *background, *seed),
        Filter::MosaicTiles {
            tile_size,
            grout_width,
            lighten_grout,
            seed,
        } => texture::mosaic_tiles(buf, *tile_size, *grout_width, *lighten_grout, *seed),
        Filter::Patchwork {
            square_size,
            relief,
            seed,
        } => texture::patchwork(buf, *square_size, *relief, *seed),
        Filter::StainedGlass {
            cell_size,
            border_thickness,
            light_intensity,
            foreground,
            seed,
        } => texture::stained_glass(
            buf,
            *cell_size,
            *border_thickness,
            *light_intensity,
            *foreground,
            *seed,
        ),
        Filter::Texturizer { texture } => texture::texturizer(buf, *texture),
        Filter::OilPaint {
            stylization,
            cleanliness,
            scale,
            bristle_detail,
            angular_direction,
            shine,
        } => oil_paint::oil_paint(
            buf,
            *stylization,
            *cleanliness,
            *scale,
            *bristle_detail,
            *angular_direction,
            *shine,
        ),
        Filter::DustAndScratches { radius, threshold } => {
            noise::dust_and_scratches(buf, *radius, *threshold)
        }
        Filter::Extrude {
            kind,
            size,
            depth,
            level_based,
            solid_front,
            mask_incomplete,
        } => stylize::extrude(
            buf,
            *kind,
            *size,
            *depth,
            *level_based,
            *solid_front,
            *mask_incomplete,
        ),
        Filter::Tiles {
            count,
            offset,
            fill,
            foreground,
            background,
        } => stylize::tiles(buf, *count, *offset, *fill, *foreground, *background),
        Filter::TraceContour { level, edge } => stylize::trace_contour(buf, *level, *edge),
        Filter::Wind { method, from_right } => stylize::wind(buf, *method, *from_right),
        Filter::SmartSharpen {
            amount,
            radius,
            reduce_noise,
            remove,
            angle,
            more_accurate,
            shadow,
            highlight,
        } => sharpen::smart_sharpen(
            buf,
            *amount,
            *radius,
            *reduce_noise,
            *remove,
            *angle,
            *more_accurate,
            *shadow,
            *highlight,
        ),
    }
}
