use pictura_core::PixelBuffer;

use crate::{
    artistic, blur, brush_strokes, distort, noise, oil_paint, other, pixelate, render, sharpen,
    sketch, stylize, texture, validate, BrushType, FilterError, GrainType, HalftoneType, LensType,
    LightDirection, MezzotintType, NoiseDistribution, PolarKind, Quality, RadialMethod, RippleSize,
    ShearFill, SpherizeMode, StrokeDirection, TextureOptions, WaveType, ZigZagStyle,
};

#[derive(Debug, Clone, PartialEq)]
pub enum Filter {
    GaussianBlur {
        radius: f64,
    },
    BoxBlur {
        radius: u32,
    },
    MotionBlur {
        angle: f64,
        distance: u32,
    },
    RadialBlur {
        method: RadialMethod,
        amount: f64,
        quality: Quality,
    },
    Average,
    Blur,
    BlurMore,
    SurfaceBlur {
        radius: u32,
        threshold: u8,
    },
    Sharpen,
    SharpenMore,
    SharpenEdges,
    UnsharpMask {
        amount: f64,
        radius: f64,
        threshold: u8,
    },
    AddNoise {
        amount: f64,
        distribution: NoiseDistribution,
        monochromatic: bool,
        seed: u64,
    },
    Median {
        radius: u32,
    },
    Despeckle,
    Maximum {
        radius: u32,
    },
    Minimum {
        radius: u32,
    },
    Offset {
        horizontal: i32,
        vertical: i32,
        wrap: bool,
        background: [u8; 3],
    },
    HighPass {
        radius: f64,
    },
    Custom {
        kernel: [[f64; 5]; 5],
        scale: f64,
        offset: f64,
    },
    Emboss {
        angle: f64,
        height: f64,
        amount: f64,
    },
    FindEdges,
    Solarize,
    Mosaic {
        cell_size: u32,
    },
    Crystallize {
        cell_size: u32,
        seed: u64,
    },
    Facet,
    Fragment,
    Mezzotint {
        kind: MezzotintType,
        seed: u64,
    },
    Pointillize {
        cell_size: u32,
        background: [u8; 3],
        seed: u64,
    },
    ColorHalftone {
        max_radius: u32,
        angles: [f64; 4],
    },
    Twirl {
        angle: f64,
    },
    Pinch {
        amount: f64,
    },
    Spherize {
        amount: f64,
        mode: SpherizeMode,
    },
    Ripple {
        amount: f64,
        size: RippleSize,
    },
    Wave {
        generators: u32,
        wavelength: (f64, f64),
        amplitude: (f64, f64),
        kind: WaveType,
        scale: (f64, f64),
        seed: u64,
        repeat_edge: bool,
    },
    PolarCoordinates {
        kind: PolarKind,
    },
    Shear {
        curve: Vec<(f64, f64)>,
        fill: ShearFill,
    },
    ZigZag {
        amount: f64,
        ridges: u32,
        style: ZigZagStyle,
    },
    OceanRipple {
        size: u32,
        magnitude: u32,
        seed: u64,
    },
    Clouds {
        color_a: [u8; 3],
        color_b: [u8; 3],
        starker: bool,
        seed: u64,
    },
    DifferenceClouds {
        color_a: [u8; 3],
        color_b: [u8; 3],
        starker: bool,
        seed: u64,
    },
    Fibers {
        variance: f64,
        strength: f64,
        color_a: [u8; 3],
        color_b: [u8; 3],
        seed: u64,
    },
    LensFlare {
        brightness: f64,
        center: (f64, f64),
        lens: LensType,
    },
    Cutout {
        levels: u8,
        edge_simplicity: u8,
        edge_fidelity: u8,
    },
    FilmGrain {
        grain: u8,
        highlight_area: u8,
        intensity: u8,
        seed: u64,
    },
    NeonGlow {
        glow_size: i32,
        glow_brightness: u8,
        glow_color: [u8; 3],
    },
    PosterEdges {
        edge_thickness: u8,
        edge_intensity: u8,
        posterization: u8,
    },
    PaintDaubs {
        brush_size: u8,
        sharpness: u8,
        brush_type: BrushType,
        seed: u64,
    },
    PaletteKnife {
        stroke_size: u8,
        stroke_detail: u8,
        softness: u8,
        seed: u64,
    },
    PlasticWrap {
        highlight_strength: u8,
        detail: u8,
        smoothness: u8,
    },
    Sponge {
        brush_size: u8,
        definition: u8,
        smoothness: u8,
        seed: u64,
    },
    ColoredPencil {
        pencil_width: u8,
        stroke_pressure: u8,
        paper_brightness: u8,
        foreground: [u8; 3],
        background: [u8; 3],
        seed: u64,
    },
    DryBrush {
        brush_size: u8,
        brush_detail: u8,
        texture: u8,
        seed: u64,
    },
    Fresco {
        brush_size: u8,
        brush_detail: u8,
        texture: u8,
        seed: u64,
    },
    RoughPastels {
        stroke_length: u8,
        stroke_detail: u8,
        texture: TextureOptions,
        foreground: [u8; 3],
        background: [u8; 3],
        seed: u64,
    },
    SmudgeStick {
        stroke_length: u8,
        highlight_area: u8,
        intensity: u8,
        seed: u64,
    },
    Underpainting {
        brush_size: u8,
        texture_coverage: u8,
        texture: TextureOptions,
        seed: u64,
    },
    Watercolor {
        brush_detail: u8,
        shadow_intensity: u8,
        texture: u8,
        foreground: [u8; 3],
        background: [u8; 3],
        seed: u64,
    },
    AccentedEdges {
        edge_width: u8,
        edge_brightness: u8,
        smoothness: u8,
    },
    AngledStrokes {
        direction_balance: u8,
        stroke_length: u8,
        sharpness: u8,
    },
    Crosshatch {
        stroke_length: u8,
        sharpness: u8,
        strength: u8,
    },
    DarkStrokes {
        balance: u8,
        black_intensity: u8,
        white_intensity: u8,
    },
    InkOutlines {
        stroke_length: u8,
        dark_intensity: u8,
        light_intensity: u8,
    },
    Spatter {
        spray_radius: u8,
        smoothness: u8,
        seed: u64,
    },
    SprayedStrokes {
        stroke_length: u8,
        spray_radius: u8,
        direction: StrokeDirection,
        seed: u64,
    },
    SumiE {
        stroke_width: u8,
        stroke_pressure: u8,
        contrast: u8,
    },
    BasRelief {
        detail: u8,
        smoothness: u8,
        light_direction: LightDirection,
        foreground: [u8; 3],
        background: [u8; 3],
    },
    ChalkCharcoal {
        charcoal_area: u8,
        chalk_area: u8,
        stroke_pressure: u8,
        foreground: [u8; 3],
        background: [u8; 3],
        seed: u64,
    },
    Charcoal {
        thickness: u8,
        detail: u8,
        light_dark_balance: u8,
        foreground: [u8; 3],
        background: [u8; 3],
        seed: u64,
    },
    Chrome {
        detail: u8,
        smoothness: u8,
    },
    ConteCrayon {
        foreground_level: u8,
        background_level: u8,
        texture: TextureOptions,
        foreground: [u8; 3],
        background: [u8; 3],
        seed: u64,
    },
    GraphicPen {
        stroke_length: u8,
        light_dark_balance: u8,
        direction: StrokeDirection,
        foreground: [u8; 3],
        background: [u8; 3],
    },
    HalftonePattern {
        size: u8,
        contrast: u8,
        pattern: HalftoneType,
    },
    NotePaper {
        image_balance: u8,
        graininess: u8,
        relief: u8,
        seed: u64,
    },
    Photocopy {
        detail: u8,
        darkness: u8,
    },
    Plaster {
        image_balance: u8,
        smoothness: u8,
        light_direction: LightDirection,
        foreground: [u8; 3],
        background: [u8; 3],
    },
    Reticulation {
        density: u8,
        black_level: u8,
        white_level: u8,
        foreground: [u8; 3],
        background: [u8; 3],
        seed: u64,
    },
    Stamp {
        light_dark_balance: u8,
        smoothness: u8,
        foreground: [u8; 3],
        background: [u8; 3],
    },
    TornEdges {
        image_balance: u8,
        smoothness: u8,
        contrast: u8,
        foreground: [u8; 3],
        background: [u8; 3],
    },
    WaterPaper {
        fiber_length: u8,
        brightness: u8,
        contrast: u8,
        seed: u64,
    },
    Craquelure {
        crack_spacing: u8,
        crack_depth: u8,
        crack_brightness: u8,
    },
    Grain {
        intensity: u8,
        contrast: u8,
        grain_type: GrainType,
        background: [u8; 3],
        seed: u64,
    },
    MosaicTiles {
        tile_size: u8,
        grout_width: u8,
        lighten_grout: u8,
        seed: u64,
    },
    Patchwork {
        square_size: u8,
        relief: u8,
        seed: u64,
    },
    StainedGlass {
        cell_size: u8,
        border_thickness: u8,
        light_intensity: u8,
        foreground: [u8; 3],
        seed: u64,
    },
    Texturizer {
        texture: TextureOptions,
    },
    OilPaint {
        stylization: f64,
        cleanliness: f64,
        scale: f64,
        bristle_detail: f64,
        angular_direction: f64,
        shine: f64,
    },
}

/// Apply `filter` in place (planar 8-bit; channels 3 or 4; alpha untouched).
pub fn apply(filter: &Filter, buf: &mut PixelBuffer) -> Result<(), FilterError> {
    validate(buf)?;
    match filter {
        Filter::GaussianBlur { radius } => blur::gaussian(buf, *radius),
        Filter::BoxBlur { radius } => blur::r#box(buf, *radius),
        Filter::MotionBlur { angle, distance } => blur::motion(buf, *angle, *distance),
        Filter::RadialBlur {
            method,
            amount,
            quality,
        } => blur::radial(buf, *method, *amount, *quality),
        Filter::Average => blur::average(buf),
        Filter::Blur => blur::simple(buf, false),
        Filter::BlurMore => blur::simple(buf, true),
        Filter::SurfaceBlur { radius, threshold } => blur::surface(buf, *radius, *threshold),
        Filter::Sharpen => sharpen::sharpen(buf),
        Filter::SharpenMore => sharpen::sharpen_more(buf),
        Filter::SharpenEdges => sharpen::edges(buf),
        Filter::UnsharpMask {
            amount,
            radius,
            threshold,
        } => sharpen::unsharp_mask(buf, *amount, *radius, *threshold),
        Filter::AddNoise {
            amount,
            distribution,
            monochromatic,
            seed,
        } => noise::add(buf, *amount, *distribution, *monochromatic, *seed),
        Filter::Median { radius } => noise::median(buf, *radius),
        Filter::Despeckle => noise::despeckle(buf),
        Filter::Maximum { radius } => other::maximum(buf, *radius),
        Filter::Minimum { radius } => other::minimum(buf, *radius),
        Filter::Offset {
            horizontal,
            vertical,
            wrap,
            background,
        } => other::offset(buf, *horizontal, *vertical, *wrap, *background),
        Filter::HighPass { radius } => other::high_pass(buf, *radius),
        Filter::Custom {
            kernel,
            scale,
            offset,
        } => other::custom(buf, kernel, *scale, *offset),
        Filter::Emboss {
            angle,
            height,
            amount,
        } => stylize::emboss(buf, *angle, *height, *amount),
        Filter::FindEdges => stylize::find_edges(buf),
        Filter::Solarize => stylize::solarize(buf),
        Filter::Mosaic { cell_size } => pixelate::mosaic(buf, *cell_size),
        Filter::Crystallize { cell_size, seed } => pixelate::crystallize(buf, *cell_size, *seed),
        Filter::Facet => pixelate::facet(buf),
        Filter::Fragment => pixelate::fragment(buf),
        Filter::Mezzotint { kind, seed } => pixelate::mezzotint(buf, *kind, *seed),
        Filter::Pointillize {
            cell_size,
            background,
            seed,
        } => pixelate::pointillize(buf, *cell_size, *background, *seed),
        Filter::ColorHalftone { max_radius, angles } => {
            pixelate::color_halftone(buf, *max_radius, *angles)
        }
        Filter::Twirl { angle } => distort::twirl(buf, *angle),
        Filter::Pinch { amount } => distort::pinch(buf, *amount),
        Filter::Spherize { amount, mode } => distort::spherize(buf, *amount, *mode),
        Filter::Ripple { amount, size } => distort::ripple(buf, *amount, *size),
        Filter::Wave {
            generators,
            wavelength,
            amplitude,
            kind,
            scale,
            seed,
            repeat_edge,
        } => distort::wave(
            buf,
            *generators,
            *wavelength,
            *amplitude,
            *kind,
            *scale,
            *seed,
            *repeat_edge,
        ),
        Filter::PolarCoordinates { kind } => distort::polar_coordinates(buf, *kind),
        Filter::Shear { curve, fill } => distort::shear(buf, curve, *fill),
        Filter::ZigZag {
            amount,
            ridges,
            style,
        } => distort::zigzag(buf, *amount, *ridges, *style),
        Filter::OceanRipple {
            size,
            magnitude,
            seed,
        } => distort::ocean_ripple(buf, *size, *magnitude, *seed),
        Filter::Clouds {
            color_a,
            color_b,
            starker,
            seed,
        } => render::clouds(buf, *color_a, *color_b, *starker, *seed),
        Filter::DifferenceClouds {
            color_a,
            color_b,
            starker,
            seed,
        } => render::difference_clouds(buf, *color_a, *color_b, *starker, *seed),
        Filter::Fibers {
            variance,
            strength,
            color_a,
            color_b,
            seed,
        } => render::fibers(buf, *variance, *strength, *color_a, *color_b, *seed),
        Filter::LensFlare {
            brightness,
            center,
            lens,
        } => render::lens_flare(buf, *brightness, *center, *lens),
        Filter::Cutout {
            levels,
            edge_simplicity,
            edge_fidelity,
        } => artistic::cutout(buf, *levels, *edge_simplicity, *edge_fidelity),
        Filter::FilmGrain {
            grain,
            highlight_area,
            intensity,
            seed,
        } => artistic::film_grain(buf, *grain, *highlight_area, *intensity, *seed),
        Filter::NeonGlow {
            glow_size,
            glow_brightness,
            glow_color,
        } => artistic::neon_glow(buf, *glow_size, *glow_brightness, *glow_color),
        Filter::PosterEdges {
            edge_thickness,
            edge_intensity,
            posterization,
        } => artistic::poster_edges(buf, *edge_thickness, *edge_intensity, *posterization),
        Filter::PaintDaubs {
            brush_size,
            sharpness,
            brush_type,
            seed,
        } => artistic::paint_daubs(buf, *brush_size, *sharpness, *brush_type, *seed),
        Filter::PaletteKnife {
            stroke_size,
            stroke_detail,
            softness,
            seed,
        } => artistic::palette_knife(buf, *stroke_size, *stroke_detail, *softness, *seed),
        Filter::PlasticWrap {
            highlight_strength,
            detail,
            smoothness,
        } => artistic::plastic_wrap(buf, *highlight_strength, *detail, *smoothness),
        Filter::Sponge {
            brush_size,
            definition,
            smoothness,
            seed,
        } => artistic::sponge(buf, *brush_size, *definition, *smoothness, *seed),
        Filter::ColoredPencil {
            pencil_width,
            stroke_pressure,
            paper_brightness,
            foreground,
            background,
            seed,
        } => artistic::colored_pencil(
            buf,
            *pencil_width,
            *stroke_pressure,
            *paper_brightness,
            *foreground,
            *background,
            *seed,
        ),
        Filter::DryBrush {
            brush_size,
            brush_detail,
            texture,
            seed,
        } => artistic::dry_brush(buf, *brush_size, *brush_detail, *texture, *seed),
        Filter::Fresco {
            brush_size,
            brush_detail,
            texture,
            seed,
        } => artistic::fresco(buf, *brush_size, *brush_detail, *texture, *seed),
        Filter::RoughPastels {
            stroke_length,
            stroke_detail,
            texture,
            foreground,
            background,
            seed,
        } => artistic::rough_pastels(
            buf,
            *stroke_length,
            *stroke_detail,
            *texture,
            *foreground,
            *background,
            *seed,
        ),
        Filter::SmudgeStick {
            stroke_length,
            highlight_area,
            intensity,
            seed,
        } => artistic::smudge_stick(buf, *stroke_length, *highlight_area, *intensity, *seed),
        Filter::Underpainting {
            brush_size,
            texture_coverage,
            texture,
            seed,
        } => artistic::underpainting(buf, *brush_size, *texture_coverage, *texture, *seed),
        Filter::Watercolor {
            brush_detail,
            shadow_intensity,
            texture,
            foreground,
            background,
            seed,
        } => artistic::watercolor(
            buf,
            *brush_detail,
            *shadow_intensity,
            *texture,
            *foreground,
            *background,
            *seed,
        ),
        Filter::AccentedEdges {
            edge_width,
            edge_brightness,
            smoothness,
        } => brush_strokes::accented_edges(buf, *edge_width, *edge_brightness, *smoothness),
        Filter::AngledStrokes {
            direction_balance,
            stroke_length,
            sharpness,
        } => brush_strokes::angled_strokes(buf, *direction_balance, *stroke_length, *sharpness),
        Filter::Crosshatch {
            stroke_length,
            sharpness,
            strength,
        } => brush_strokes::crosshatch(buf, *stroke_length, *sharpness, *strength),
        Filter::DarkStrokes {
            balance,
            black_intensity,
            white_intensity,
        } => brush_strokes::dark_strokes(buf, *balance, *black_intensity, *white_intensity),
        Filter::InkOutlines {
            stroke_length,
            dark_intensity,
            light_intensity,
        } => brush_strokes::ink_outlines(buf, *stroke_length, *dark_intensity, *light_intensity),
        Filter::Spatter {
            spray_radius,
            smoothness,
            seed,
        } => brush_strokes::spatter(buf, *spray_radius, *smoothness, *seed),
        Filter::SprayedStrokes {
            stroke_length,
            spray_radius,
            direction,
            seed,
        } => brush_strokes::sprayed_strokes(buf, *stroke_length, *spray_radius, *direction, *seed),
        Filter::SumiE {
            stroke_width,
            stroke_pressure,
            contrast,
        } => brush_strokes::sumi_e(buf, *stroke_width, *stroke_pressure, *contrast),
        Filter::BasRelief {
            detail,
            smoothness,
            light_direction,
            foreground,
            background,
        } => sketch::bas_relief(
            buf,
            *detail,
            *smoothness,
            *light_direction,
            *foreground,
            *background,
        ),
        Filter::ChalkCharcoal {
            charcoal_area,
            chalk_area,
            stroke_pressure,
            foreground,
            background,
            seed,
        } => sketch::chalk_charcoal(
            buf,
            *charcoal_area,
            *chalk_area,
            *stroke_pressure,
            *foreground,
            *background,
            *seed,
        ),
        Filter::Charcoal {
            thickness,
            detail,
            light_dark_balance,
            foreground,
            background,
            seed,
        } => sketch::charcoal(
            buf,
            *thickness,
            *detail,
            *light_dark_balance,
            *foreground,
            *background,
            *seed,
        ),
        Filter::Chrome { detail, smoothness } => sketch::chrome(buf, *detail, *smoothness),
        Filter::ConteCrayon {
            foreground_level,
            background_level,
            texture,
            foreground,
            background,
            seed,
        } => sketch::conte_crayon(
            buf,
            *foreground_level,
            *background_level,
            *texture,
            *foreground,
            *background,
            *seed,
        ),
        Filter::GraphicPen {
            stroke_length,
            light_dark_balance,
            direction,
            foreground,
            background,
        } => sketch::graphic_pen(
            buf,
            *stroke_length,
            *light_dark_balance,
            *direction,
            *foreground,
            *background,
        ),
        Filter::HalftonePattern {
            size,
            contrast,
            pattern,
        } => sketch::halftone_pattern(buf, *size, *contrast, *pattern),
        Filter::NotePaper {
            image_balance,
            graininess,
            relief,
            seed,
        } => sketch::note_paper(buf, *image_balance, *graininess, *relief, *seed),
        Filter::Photocopy { detail, darkness } => sketch::photocopy(buf, *detail, *darkness),
        Filter::Plaster {
            image_balance,
            smoothness,
            light_direction,
            foreground,
            background,
        } => sketch::plaster(
            buf,
            *image_balance,
            *smoothness,
            *light_direction,
            *foreground,
            *background,
        ),
        Filter::Reticulation {
            density,
            black_level,
            white_level,
            foreground,
            background,
            seed,
        } => sketch::reticulation(
            buf,
            *density,
            *black_level,
            *white_level,
            *foreground,
            *background,
            *seed,
        ),
        Filter::Stamp {
            light_dark_balance,
            smoothness,
            foreground,
            background,
        } => sketch::stamp(
            buf,
            *light_dark_balance,
            *smoothness,
            *foreground,
            *background,
        ),
        Filter::TornEdges {
            image_balance,
            smoothness,
            contrast,
            foreground,
            background,
        } => sketch::torn_edges(
            buf,
            *image_balance,
            *smoothness,
            *contrast,
            *foreground,
            *background,
        ),
        Filter::WaterPaper {
            fiber_length,
            brightness,
            contrast,
            seed,
        } => sketch::water_paper(buf, *fiber_length, *brightness, *contrast, *seed),
        Filter::Craquelure {
            crack_spacing,
            crack_depth,
            crack_brightness,
        } => texture::craquelure(buf, *crack_spacing, *crack_depth, *crack_brightness),
        Filter::Grain {
            intensity,
            contrast,
            grain_type,
            background,
            seed,
        } => texture::grain(buf, *intensity, *contrast, *grain_type, *background, *seed),
        Filter::MosaicTiles {
            tile_size,
            grout_width,
            lighten_grout,
            seed,
        } => texture::mosaic_tiles(buf, *tile_size, *grout_width, *lighten_grout, *seed),
        Filter::Patchwork {
            square_size,
            relief,
            seed,
        } => texture::patchwork(buf, *square_size, *relief, *seed),
        Filter::StainedGlass {
            cell_size,
            border_thickness,
            light_intensity,
            foreground,
            seed,
        } => texture::stained_glass(
            buf,
            *cell_size,
            *border_thickness,
            *light_intensity,
            *foreground,
            *seed,
        ),
        Filter::Texturizer { texture } => texture::texturizer(buf, *texture),
        Filter::OilPaint {
            stylization,
            cleanliness,
            scale,
            bristle_detail,
            angular_direction,
            shine,
        } => oil_paint::oil_paint(
            buf,
            *stylization,
            *cleanliness,
            *scale,
            *bristle_detail,
            *angular_direction,
            *shine,
        ),
    }
}
