#!/usr/bin/env python3
"""Flag passages in the spec corpus that look like reproduction of source prose.

Heuristic first pass for the verbatim-expression audit: long quoted strings and
long blockquote lines are the places most likely to reproduce Adobe Help/SDK
prose rather than paraphrase facts. Short quotes (menu paths, option names,
file-format identifiers) are facts and are deliberately not flagged.

Usage:  python3 scripts/verbatim-audit.py [min_words]
Writes: docs/dev/verbatim-expression-audit-findings.md
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DOCS = ROOT / "docs"
REPORT = DOCS / "dev" / "verbatim-expression-audit-findings.md"
MIN_WORDS = int(sys.argv[1]) if len(sys.argv) > 1 else 12

ATTR = re.compile(r"Adobe|CS6 Help|Help (states|notes|says|describes|defines)|per Adobe", re.I)
QUOTED = re.compile(r'"[^"]{%d,}"' % MIN_WORDS)


def words(text: str) -> int:
    return len(re.findall(r"\S+", text))


def main() -> None:
    rows: list[tuple[int, str, int, str, str]] = []
    for path in sorted(DOCS.rglob("*.md")):
        if path.name == "verbatim-expression-audit-findings.md":
            continue  # the scanner's own output embeds the flagged passages
        rel = path.relative_to(ROOT)
        for lineno, line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
            stripped = line.strip()
            if stripped.startswith(">"):
                body = stripped.lstrip("> ").strip()
                if words(body) >= MIN_WORDS * 2:
                    rows.append((words(body), str(rel), lineno, "blockquote", body))
            for match in QUOTED.finditer(line):
                body = match.group(0)
                if words(body) >= MIN_WORDS:
                    kind = "quote+attr" if ATTR.search(line) else "quote"
                    rows.append((words(body), str(rel), lineno, kind, body))

    rows.sort(reverse=True)
    lines = [
        "# Verbatim-expression audit — findings",
        "",
        "Generated by `scripts/verbatim-audit.py`; re-run after edits. This flags",
        "long quoted strings and long blockquotes, ranked by length. Passages are",
        "NOT reproduced here (that would re-introduce the quoted text); open the",
        "cited file:line to review each one.",
        "",
        f"Threshold: quote >= {MIN_WORDS} words; blockquote >= {MIN_WORDS * 2} words.",
        f"Flagged passages: {len(rows)}",
        "",
        "| Words | File:line | Kind |",
        "|---|---|---|",
    ]
    for wc, rel, lineno, kind, _body in rows:
        lines.append(f"| {wc} | `{rel}:{lineno}` | {kind} |")
    lines.append("")
    REPORT.write_text("\n".join(lines), encoding="utf-8")
    print(f"flagged {len(rows)} passages -> {REPORT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
